name:                LifeOfMatt
version:             0.1.0.0
github:              "githubuser/LifeOfMatt"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/LifeOfMatt#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- aeson
- lens
- lens-aeson
- time
- PyF
- vector
- containers
- directory


library:
  source-dirs: src

executables:
  LifeOfMatt:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LifeOfMatt
