-- Autogenerated from src/Elm/Render/Fitness.hs
module Fitness.Autogen.Fitness exposing (view)

import Plotting.BarCharts exposing (stackedBarChart)
import Css exposing (..)
import Html.Styled exposing (..)
import Html.Styled.Attributes exposing (class, css, href, src)
import Html.Styled.Events exposing (onClick)

selector =
  div
  [ css
    [ position absolute
    , left (px 205)
    , bottom (px -200)
    ]
  ]
  [ select []
    [ option [] [ text "A" ]
    , option [] [ text "B" ]
    , option [] [ text "C" ]
    , option [] [ text "D" ]
    ]
  ]

view : Html msg
view =
  div
  [ class "container" ]
  [ h1 [ css
        [ textAlign center
        , padding (px 20)
        ]
      ] [ text "2020-05-23" ]
  , fromUnstyled <|
     stackedBarChart
       (List.map .day data)
       (List.map (\{ label, accessor } -> ( label, List.map accessor data )) series)
  , form
    [ css [ padding (px 20)] ]
    [ select  []
      [ option [] [ text "A" ]
      , option [] [ text "B" ]
      , option [] [ text "C" ]
      , option [] [ text "D" ]
      ]
    ]
  ]

type alias Workout =
  { day : Int
  , run: Float 
  , trailrun: Float 
  , abs: Float 
  , yoga: Float 
  , bouldering: Float 
  , rollout: Float 
  , wriststabilizer: Float 
  , shoulderstabili: Float 
  , hangboardminimu: Float
  }

series : List { label : String, accessor : Workout -> Float }
series =
  [ {label = "Run", accessor = .run}
  , {label = "TrailRun", accessor = .trailrun}
  , {label = "Abs", accessor = .abs}
  , {label = "Yoga", accessor = .yoga}
  , {label = "Bouldering", accessor = .bouldering}
  , {label = "RollOut", accessor = .rollout}
  , {label = "WristStabilizer", accessor = .wriststabilizer}
  , {label = "ShoulderStabili", accessor = .shoulderstabili}
  , {label = "HangboardMinimu", accessor = .hangboardminimu}
  ]

data =
  [ Workout 1 1.82 0.00 0.35 0.00 0.75 0.15 0.21 0.21 0.00
  , Workout 2 1.17 0.00 0.00 0.00 0.00 0.29 0.00 0.00 0.00
  , Workout 3 0.00 1.33 0.21 0.00 0.00 0.00 0.20 0.20 0.16
  , Workout 4 1.53 0.00 0.00 0.97 0.00 0.00 0.00 0.00 0.00
  , Workout 5 1.75 0.00 0.00 0.00 0.00 0.12 0.00 0.00 0.00
  , Workout 6 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
  , Workout 7 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
  ]

