-- Autogenerated from src/Elm/Render/Running.hs
module Fitness.Autogen.Running exposing (view)

import Plotting.LinePlots exposing (simpleLinePlot)

import Html exposing (..)
import Html.Attributes exposing (class)

type alias RunningMetrics =
  { day : Float
  , miles : Float
  , totalTime : Float
  }

view : Html.Html msg
view =
  Html.div
  [ class "container" ]
  [ 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 47"  ]
      , ol []
        [ li [] [ text "Total Miles: 5.06" ]
        , li [] [ text "Total Elevation: 169.40" ]
        , li [] [ text "Meters/HeartBeat: 2.02" ]
        , li [] [ text "Total Time: 0:55" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 46"  ]
      , ol []
        [ li [] [ text "Total Miles: 9.62" ]
        , li [] [ text "Total Elevation: 405.00" ]
        , li [] [ text "Meters/HeartBeat: 1.86" ]
        , li [] [ text "Total Time: 1:38" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 45"  ]
      , ol []
        [ li [] [ text "Total Miles: 2.77" ]
        , li [] [ text "Total Elevation: 50.80" ]
        , li [] [ text "Meters/HeartBeat: 1.85" ]
        , li [] [ text "Total Time: 0:29" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 44"  ]
      , ol []
        [ li [] [ text "Total Miles: 6.06" ]
        , li [] [ text "Total Elevation: 230.40" ]
        , li [] [ text "Meters/HeartBeat: 1.84" ]
        , li [] [ text "Total Time: 1:16" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 43"  ]
      , ol []
        [ li [] [ text "Total Miles: 0.00" ]
        , li [] [ text "Total Elevation: 0.00" ]
        , li [] [ text "Meters/HeartBeat: nan" ]
        , li [] [ text "Total Time: 0:0" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 42"  ]
      , ol []
        [ li [] [ text "Total Miles: 0.00" ]
        , li [] [ text "Total Elevation: 0.00" ]
        , li [] [ text "Meters/HeartBeat: nan" ]
        , li [] [ text "Total Time: 0:0" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 41"  ]
      , ol []
        [ li [] [ text "Total Miles: 0.00" ]
        , li [] [ text "Total Elevation: 0.00" ]
        , li [] [ text "Meters/HeartBeat: nan" ]
        , li [] [ text "Total Time: 0:0" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 40"  ]
      , ol []
        [ li [] [ text "Total Miles: 0.00" ]
        , li [] [ text "Total Elevation: 0.00" ]
        , li [] [ text "Meters/HeartBeat: nan" ]
        , li [] [ text "Total Time: 0:0" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 39"  ]
      , ol []
        [ li [] [ text "Total Miles: 4.76" ]
        , li [] [ text "Total Elevation: 146.20" ]
        , li [] [ text "Meters/HeartBeat: 1.87" ]
        , li [] [ text "Total Time: 0:49" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 38"  ]
      , ol []
        [ li [] [ text "Total Miles: 0.00" ]
        , li [] [ text "Total Elevation: 0.00" ]
        , li [] [ text "Meters/HeartBeat: nan" ]
        , li [] [ text "Total Time: 0:0" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 37"  ]
      , ol []
        [ li [] [ text "Total Miles: 0.00" ]
        , li [] [ text "Total Elevation: 0.00" ]
        , li [] [ text "Meters/HeartBeat: nan" ]
        , li [] [ text "Total Time: 0:0" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 36"  ]
      , ol []
        [ li [] [ text "Total Miles: 0.00" ]
        , li [] [ text "Total Elevation: 0.00" ]
        , li [] [ text "Meters/HeartBeat: nan" ]
        , li [] [ text "Total Time: 0:0" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 35"  ]
      , ol []
        [ li [] [ text "Total Miles: 0.00" ]
        , li [] [ text "Total Elevation: 0.00" ]
        , li [] [ text "Meters/HeartBeat: nan" ]
        , li [] [ text "Total Time: 0:0" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 34"  ]
      , ol []
        [ li [] [ text "Total Miles: 0.00" ]
        , li [] [ text "Total Elevation: 0.00" ]
        , li [] [ text "Meters/HeartBeat: nan" ]
        , li [] [ text "Total Time: 0:0" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 33"  ]
      , ol []
        [ li [] [ text "Total Miles: 0.00" ]
        , li [] [ text "Total Elevation: 0.00" ]
        , li [] [ text "Meters/HeartBeat: nan" ]
        , li [] [ text "Total Time: 0:0" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 32"  ]
      , ol []
        [ li [] [ text "Total Miles: 0.00" ]
        , li [] [ text "Total Elevation: 0.00" ]
        , li [] [ text "Meters/HeartBeat: nan" ]
        , li [] [ text "Total Time: 0:0" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 31"  ]
      , ol []
        [ li [] [ text "Total Miles: 0.00" ]
        , li [] [ text "Total Elevation: 0.00" ]
        , li [] [ text "Meters/HeartBeat: nan" ]
        , li [] [ text "Total Time: 0:0" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 30"  ]
      , ol []
        [ li [] [ text "Total Miles: 0.00" ]
        , li [] [ text "Total Elevation: 0.00" ]
        , li [] [ text "Meters/HeartBeat: nan" ]
        , li [] [ text "Total Time: 0:0" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 29"  ]
      , ol []
        [ li [] [ text "Total Miles: 5.18" ]
        , li [] [ text "Total Elevation: 141.40" ]
        , li [] [ text "Meters/HeartBeat: 2.28" ]
        , li [] [ text "Total Time: 0:45" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 28"  ]
      , ol []
        [ li [] [ text "Total Miles: 1.53" ]
        , li [] [ text "Total Elevation: 35.80" ]
        , li [] [ text "Meters/HeartBeat: 2.20" ]
        , li [] [ text "Total Time: 0:13" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 27"  ]
      , ol []
        [ li [] [ text "Total Miles: 3.41" ]
        , li [] [ text "Total Elevation: 62.20" ]
        , li [] [ text "Meters/HeartBeat: 2.36" ]
        , li [] [ text "Total Time: 0:30" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 26"  ]
      , ol []
        [ li [] [ text "Total Miles: 0.00" ]
        , li [] [ text "Total Elevation: 0.00" ]
        , li [] [ text "Meters/HeartBeat: nan" ]
        , li [] [ text "Total Time: 0:0" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 25"  ]
      , ol []
        [ li [] [ text "Total Miles: 0.00" ]
        , li [] [ text "Total Elevation: 0.00" ]
        , li [] [ text "Meters/HeartBeat: nan" ]
        , li [] [ text "Total Time: 0:0" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 24"  ]
      , ol []
        [ li [] [ text "Total Miles: 7.40" ]
        , li [] [ text "Total Elevation: 228.00" ]
        , li [] [ text "Meters/HeartBeat: 2.11" ]
        , li [] [ text "Total Time: 1:11" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 23"  ]
      , ol []
        [ li [] [ text "Total Miles: 26.26" ]
        , li [] [ text "Total Elevation: 1231.20" ]
        , li [] [ text "Meters/HeartBeat: 1.84" ]
        , li [] [ text "Total Time: 4:30" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 22"  ]
      , ol []
        [ li [] [ text "Total Miles: 29.76" ]
        , li [] [ text "Total Elevation: 512.20" ]
        , li [] [ text "Meters/HeartBeat: 2.23" ]
        , li [] [ text "Total Time: 4:27" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 21"  ]
      , ol []
        [ li [] [ text "Total Miles: 49.66" ]
        , li [] [ text "Total Elevation: 1743.00" ]
        , li [] [ text "Meters/HeartBeat: 2.13" ]
        , li [] [ text "Total Time: 7:36" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 20"  ]
      , ol []
        [ li [] [ text "Total Miles: 57.57" ]
        , li [] [ text "Total Elevation: 1606.40" ]
        , li [] [ text "Meters/HeartBeat: 2.18" ]
        , li [] [ text "Total Time: 8:21" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 19"  ]
      , ol []
        [ li [] [ text "Total Miles: 56.98" ]
        , li [] [ text "Total Elevation: 2246.20" ]
        , li [] [ text "Meters/HeartBeat: 1.99" ]
        , li [] [ text "Total Time: 9:0" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 18"  ]
      , ol []
        [ li [] [ text "Total Miles: 44.15" ]
        , li [] [ text "Total Elevation: 1539.40" ]
        , li [] [ text "Meters/HeartBeat: 2.13" ]
        , li [] [ text "Total Time: 6:14" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 17"  ]
      , ol []
        [ li [] [ text "Total Miles: 45.70" ]
        , li [] [ text "Total Elevation: 982.80" ]
        , li [] [ text "Meters/HeartBeat: 2.27" ]
        , li [] [ text "Total Time: 6:27" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 16"  ]
      , ol []
        [ li [] [ text "Total Miles: 41.58" ]
        , li [] [ text "Total Elevation: 1473.80" ]
        , li [] [ text "Meters/HeartBeat: 2.15" ]
        , li [] [ text "Total Time: 6:16" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 15"  ]
      , ol []
        [ li [] [ text "Total Miles: 43.45" ]
        , li [] [ text "Total Elevation: 963.80" ]
        , li [] [ text "Meters/HeartBeat: 2.18" ]
        , li [] [ text "Total Time: 6:17" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 14"  ]
      , ol []
        [ li [] [ text "Total Miles: 42.07" ]
        , li [] [ text "Total Elevation: 2081.80" ]
        , li [] [ text "Meters/HeartBeat: 1.83" ]
        , li [] [ text "Total Time: 7:32" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 13"  ]
      , ol []
        [ li [] [ text "Total Miles: 40.10" ]
        , li [] [ text "Total Elevation: 2108.80" ]
        , li [] [ text "Meters/HeartBeat: 1.85" ]
        , li [] [ text "Total Time: 6:49" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 12"  ]
      , ol []
        [ li [] [ text "Total Miles: 17.57" ]
        , li [] [ text "Total Elevation: 270.60" ]
        , li [] [ text "Meters/HeartBeat: 2.45" ]
        , li [] [ text "Total Time: 2:11" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 11"  ]
      , ol []
        [ li [] [ text "Total Miles: 52.33" ]
        , li [] [ text "Total Elevation: 952.60" ]
        , li [] [ text "Meters/HeartBeat: 2.37" ]
        , li [] [ text "Total Time: 6:58" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 10"  ]
      , ol []
        [ li [] [ text "Total Miles: 32.40" ]
        , li [] [ text "Total Elevation: 539.00" ]
        , li [] [ text "Meters/HeartBeat: 2.34" ]
        , li [] [ text "Total Time: 4:17" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 9"  ]
      , ol []
        [ li [] [ text "Total Miles: 43.49" ]
        , li [] [ text "Total Elevation: 714.20" ]
        , li [] [ text "Meters/HeartBeat: 2.33" ]
        , li [] [ text "Total Time: 5:43" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 8"  ]
      , ol []
        [ li [] [ text "Total Miles: 27.10" ]
        , li [] [ text "Total Elevation: 724.20" ]
        , li [] [ text "Meters/HeartBeat: 2.01" ]
        , li [] [ text "Total Time: 4:42" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 7"  ]
      , ol []
        [ li [] [ text "Total Miles: 36.52" ]
        , li [] [ text "Total Elevation: 1111.60" ]
        , li [] [ text "Meters/HeartBeat: 2.18" ]
        , li [] [ text "Total Time: 4:59" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 6"  ]
      , ol []
        [ li [] [ text "Total Miles: 11.83" ]
        , li [] [ text "Total Elevation: 188.40" ]
        , li [] [ text "Meters/HeartBeat: 2.26" ]
        , li [] [ text "Total Time: 1:36" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 5"  ]
      , ol []
        [ li [] [ text "Total Miles: 0.00" ]
        , li [] [ text "Total Elevation: 0.00" ]
        , li [] [ text "Meters/HeartBeat: nan" ]
        , li [] [ text "Total Time: 0:0" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 4"  ]
      , ol []
        [ li [] [ text "Total Miles: 0.00" ]
        , li [] [ text "Total Elevation: 0.00" ]
        , li [] [ text "Meters/HeartBeat: nan" ]
        , li [] [ text "Total Time: 0:0" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 3"  ]
      , ol []
        [ li [] [ text "Total Miles: 18.58" ]
        , li [] [ text "Total Elevation: 279.80" ]
        , li [] [ text "Meters/HeartBeat: 2.46" ]
        , li [] [ text "Total Time: 2:19" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 2"  ]
      , ol []
        [ li [] [ text "Total Miles: 27.49" ]
        , li [] [ text "Total Elevation: 593.60" ]
        , li [] [ text "Meters/HeartBeat: 2.12" ]
        , li [] [ text "Total Time: 3:42" ]
        ]
      ]

  , 
      Html.div
      [ class "container" ]
      [ h1 [] [ text "2020 1"  ]
      , ol []
        [ li [] [ text "Total Miles: 10.37" ]
        , li [] [ text "Total Elevation: 467.00" ]
        , li [] [ text "Meters/HeartBeat: 1.52" ]
        , li [] [ text "Total Time: 1:50" ]
        ]
      ]

  ]

