-- Autogenerated from src/Elm/Render/Running.hs
module Fitness.Autogen.Running exposing (view)

import Plotting.LinePlots exposing (simpleLinePlot)

import Html exposing (..)
import Html.Attributes exposing (class)

view : model -> Html.Html msg
view _ =
  Html.div
    [ class "container" ]
    [ h1 [] [ text "Week 20" ]
    , ol []
      [ li [] [ text "Total Miles: 0.0" ]
      , li [] [ text "Total Time: 0:0" ]
      ]
    , simpleLinePlot "Week 20" ("Day", .day) ("Miles", .miles) thisWeek
    ]

type alias RunningMetrics =
  { day : Float
  , miles : Float
  , totalTime : Float
  }

thisWeek : List RunningMetrics
thisWeek =
  [ RunningMetrics 1 0.00 0.0
  , RunningMetrics 2 0.00 0.0
  , RunningMetrics 3 0.00 0.0
  , RunningMetrics 4 0.00 0.0
  , RunningMetrics 5 0.00 0.0
  , RunningMetrics 6 0.00 0.0
  , RunningMetrics 7 0.00 0.0
  ]

