-- Autogenerated from src/Elm/Render/Running.hs
module Running.Page exposing (view)

import Plotting.Plotting exposing (simpleLinePlot)

import Html
import Html.Attributes exposing (class)

view : model -> Html.Html msg
view _ =
  Html.div
    [ class "container" ]
    [ simpleLinePlot "Week 20" ("Day", .day) ("Miles", .miles) thisWeek
    ]

type alias RunningMetrics =
  { day : Float
  , miles : Float
  , totalTime : Float
  }

thisWeek : List RunningMetrics
thisWeek =
  [ RunningMetrics 1 12.22 1.42
  , RunningMetrics 2 0.00 0.0
  , RunningMetrics 3 0.00 0.0
  , RunningMetrics 4 0.00 0.0
  , RunningMetrics 5 0.00 0.0
  , RunningMetrics 6 0.00 0.0
  , RunningMetrics 7 0.00 0.0
  ]

